# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tejas-kale-relayr.github.io/analytics_demo_library/"

git_url = "https://github.com/tejas-kale-relayr/analytics_demo_library/tree/main/"

def custom_doc_links(name): return None
