# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to: str, is_formal: bool = True) -> str:
    """Say hello to someone"""
    if is_formal:
        return f"Hello {to}."
    else:
        return f"Hi {to}!!"